### ISSUE TITLE
Building Master Failure

### ISSUE THREAD

**Issue by er1c** [JetBrains/intellij-scala#118]
Just trying to build a vanilla plugin from a git clone and am getting: 

	$ sbt compile
	[info] Loading project definition from /Users/eric/Work/intellij-scala/project
	[info] Set current project to ScalaCommunity (in build file:/Users/eric/Work/intellij-scala/)
	[info] Updating {file:/Users/eric/Work/intellij-scala/}ScalaCommunity...
	[info] Resolving jline#jline;2.12 ...
	[info] Done updating.
	[info] Compiling 1741 Scala sources and 151 Java sources to /Users/eric/Work/intellij-scala/target/scala-2.11/classes...
	[error] /Users/eric/Work/intellij-scala/src/org/jetbrains/plugins/scala/lang/psi/impl/toplevel/typedef/SyntheticMembersInjector.scala:6: object ScalaCompilerSettings is not a member of package org.jetbrains.plugins.scala.project
	[error] import org.jetbrains.plugins.scala.project.ScalaCompilerSettings
	[error]        ^
	[error] /Users/eric/Work/intellij-scala/src/org/jetbrains/plugins/scala/lang/psi/impl/toplevel/typedef/SyntheticMembersInjector.scala:31: not found: value ScalaCompilerSettings
	[error]   private def needQQEmulation(e: PsiElement) = ScalaCompilerSettings.instanceIn(e.getProject).plugins.exists(_.contains("paradise_2.10"))
	[error]                                                ^
	[error] two errors found
	[error] (ScalaCommunity/compile:compile) Compilation failed
	[error] Total time: 72 s, completed Jan 9, 2015 2:48:14 PM

**Comment by dedoz** [comment]
Fixed in 5ff577c16f006cc996a54d8fe974a656b7722f20
