### ISSUE TITLE
Syntax errors being shown with scala.Dynamic

### ISSUE THREAD

**Issue by brendanator** [JetBrains/intellij-scala#128]
1) Import https://github.com/jhc-systems/sqlest
2) Run `sbt boilerplateGenerate` from command line
3) Open this file extractors/src/test/scala/sqlest/extractor/CaseClassExtractorMacroSpec.scala

There are several syntax errors related to scala.Dynamic. 

N.B. The extract macro is returning a Dynamic so that the Scala compiler can implicitly insert an apply method. The following are equivalent but both fail to compile:
```scala
  val simpleExtractor = extract[One](
    a = intExtractor,
    b = stringExtractor
  )


  val simpleExtractor = extract[One].apply(
    a = intExtractor,
    b = stringExtractor
  )
```

**Comment by brendanator** [comment]
A much simpler example which I think is the cause of the above problem is 
```scala
  import scala.language.dynamics
  val test = new Dynamic {}
  test.notThere
```
This should compile successfully but fail at runtime. Instead this is showing the error `Cannot resolve symbol notThere`

**Comment by Alefas** [comment]
@brendanator Your simplified example shouldn't compile as Dynamic trait doesn't have 'selectDynamic' method. This method should be resolved statically, as Dynamic trait is just syntax sugar. Looks like the problem in macros, which returns Dynamic type with 'selectDynamic' trait, so actually this can be resolved statically, but just after macroexpansion, what we've not implemented yet in Scala plugin.

**Comment by brendanator** [comment]
@Alefas Cool, that makes sense. Just to clarify, the macro is actually returning
```scala
new Dynamic {
  def apply(...) = ???
}
```

In an ideal world this would just have been:
```scala
new Object {
  def apply(...) = ???
}
```
but due to a bug in the Scala compiler the macro had to return Dynamic as apply sugaring doesn't happen after macro expansion. There's more details here: 
- [StackOverflow](https://stackoverflow.com/questions/26577588/is-there-any-workaround-for-scala-bug-si-7914-returning-an-apply-method-from-a) 
- [Scala Issue](https://issues.scala-lang.org/browse/SI-7914)

If you need any more details let me know
Cheers

**Comment by Alefas** [comment]
Is it possible to put {def apply(...)} to return type of macro? Plugin works ok with blackbox macros, we only have problems with whitebox. Which we can hardcode (in popular cases like shapeless). For general case we are working on macro interpretation.

**Comment by brendanator** [comment]
Unfortunately not. The number and type of the parameters to the apply method is not known until the macro has run. I just tried a couple of variations to see if I could get it to work but the code fails to compile in sbt

Thanks for your help on this, I will wait until the macro interpretation is working. Is there an issue I can watch for this?

**Comment by Alefas** [comment]
I created such issue: https://youtrack.jetbrains.com/issue/SCL-8355
