### ISSUE TITLE
Multi-project build with single build.sbt not works properly after updating plugin (1.3.2->1.4)

### ISSUE THREAD

**Issue by Romastyi** [JetBrains/intellij-scala#132]
With plugin version 1.4 I can't to run a subproject inside multi-project build.

Project structure is like this:

root/
|-build.sbt
|-project1/
|  |-src/
|    |-...
|-project2/
|  |-src/
|    |-...
|-...

With plugin version *1.3.2.26* a command line for run|debug *project1*, for exmaple, was:

.../java <some_options> -classpath ".../idea_rt.jar" xsbt.boot.Boot **"project project1"** run

and works perfect.

After updating to version *1.4* a new command line is:

.../java <some_options> -classpath ".../idea_rt.jar" xsbt.boot.Boot run

and it always starts in *root*.

Command lines are identical, but a parameter **"project project1"** (which switchs current project) is ommited in second one.

What can I do to run|debug subprojects separately without changing the whole project structure?

Environment Details:
Ubuntu 14.04
IntelliJ IDEA Ultimate Edition 14.0.3 Build IU 139-1117
Scala Plugin 1.4
Scala 2.11.2
SBT 0.13.7
Java 8u40

With best regards, 

Roman.

**Comment by dancingrobot84** [comment]
Hi! Thanks for the report.
Just to be precise: are you talking about "SBT Task" run configuration or something else?

**Comment by Romastyi** [comment]
Hi! Thank you for answer.
I've found some mistakes in my build.sbt definition. After some corrections all works perfectly.
And, by the way, thank you for new plugin version - it realy began to work faster.
