### ISSUE TITLE
editor shows red even though code compiles when attempting to create DBIOAction in slick 3

### ISSUE THREAD

**Issue by aruberto** [JetBrains/intellij-scala#133]
As seen in image below, result is highlighted red even though code compiles fine

![editor-error](https://cloud.githubusercontent.com/assets/9933826/6719615/2d5da94e-cd92-11e4-94bb-36b6f4829c3a.png)

Source code can be found here: https://github.com/aruberto/kingdom-of-weirdness/tree/master/slick-intellij-editor-error

Environment Details:
Intellij Community Edition 14.03
Scala Plugin 1.4
Java 8u40
Scala 2.11.6
Slick 3.0.0-RC1

**Comment by n3ziniuka5** [comment]
There is also an issue for this in jetbrains youtrack: https://youtrack.jetbrains.com/issue/SCL-8079

**Comment by Alefas** [comment]
Please watch progress in actual issue tracker: https://youtrack.jetbrains.com/issue/SCL-8079
