### ISSUE TITLE
Found an interesting failure with Miles Sabin's demo project

### ISSUE THREAD

**Issue by vpatryshev** [JetBrains/intellij-scala#134]
In his workshop, see https://github.com/milessabin/shapeless-workshop-scaladayssf-2015, the build.sbt file does not contain references to the libraries. But it does refer the scala version. As a result, when I import the project, scala plugin does not recognize the module as having scala, and does not compile it, saying "skipping Scala files without a Scala SDK in module(s)".

Of course it's easy to fix in build.sbt, but a) the message is obscure; b) it's probably not hard to add such dependencies while importing from sbt, right?

Thanks anyway.

**Comment by dancingrobot84** [comment]
Hi! Thanks for the report. Is this behaviour reproducible on metioned project without any changes or there's already fixed version in the repo? I'm asking because everything works fine for me in latest Scala plugin release.

**Comment by cjmcmurtrie** [comment]
Hi vpatryshev, may I know what you added to sbt to fix this?

I'm having a similar error on a separate project (trying to get Spark 1.2 source code to compile).

**Comment by vpatryshev** [comment]
An update. Seems like it's happening with another project.
Can't explain yet...

**Comment by vpatryshev** [comment]
Oh, an update. See http://blog.jetbrains.com/scala/2014/10/30/scala-plugin-update-for-intellij-idea-14-rc-is-out/

So, we go to project structure; Platform Setting/Global Libraries; and it's very probable that you either don't have any scala there or have an ancient version of scala library and compiler; remove the old trash, then click '+', and IntelliJ will give you a list of choices of Scala SDK (somehow not pulled from sbt automatically). Just choose the right one.

I guess the problem is with sbt import; since this is already there, we probably should replace whatever sdk is referenced from there with whatever is specified in SBT. Up to you guys.

**Comment by rpjanaka** [comment]
"scala: skipping Scala files without a Scala SDK in module(s) "

For the above error, close the IntelliJ and reopen the project using the sbt file. That resolved my issue

**Comment by nkly** [comment]
Please, consider updating Scala plugin to 1.9.2 and re-importing your projects. Scala SDK detection should be fixed there.
