### ISSUE TITLE
Unable to specify custom ScalaTest reporter

### ISSUE THREAD

**Issue by tsandall** [JetBrains/intellij-scala#141]
When specifying a custom ScalaTest reporter via the Test Options in a Run Configuration, the plugin appends "WithLocation" to the class name. It appears to be happening here:

https://github.com/JetBrains/intellij-scala/blob/1fa395eab9014f3b7ff6d8f5748a4c966d6c7127/Runners/src/org/jetbrains/plugins/scala/testingSupport/scalaTest/ScalaTestRunner.java#L98

I'm not familiar with the rest of the plugin so I cannot explain why this is happening.

**Comment by jamesbrain** [comment]
The issue has been addressed in this commit: https://github.com/JetBrains/intellij-scala/commit/e03ee58b368ab7d0a853e7e947f79aeac395ea51.
