### ISSUE TITLE
incorrect malformed format string warnings

### ISSUE THREAD

**Issue by brharrington** [JetBrains/intellij-scala#143]
Example:

```scala
"%d".format(new java.math.BigInteger("123"))
```

Leads to two warnings:

* Format specifier %d cannot be used for an argument new BigInteger("123") (BigInteger)
* Argument new BigInteger("123") (BigInteger) cannot be used for a format specifier %d

**Comment by niktrop** [comment]
Class `java.math.BigInteger` was not handled in this inspection, I fixed this. Thank you for the report!
