### ISSUE TITLE
howto compile

### ISSUE THREAD

**Issue by bblfish** [JetBrains/intellij-scala#147]
Hi, 

  there are a lot of issues with the current release 1.4.169.1.EAP working with Intellij ideaIU-141.1010.3 . I would not mind compiling the correct branch of the plugin. 

I can't open the following projects:

 * [banana-rdf](https://github.com/w3c/banana-rdf)
 * [scala-js spa tutorial](https://github.com/ochrons/scalajs-spa-tutorial)
 * And others have stated they can't open the scala-js compiler, which is written in pure scala.

If those have been fixed in the master branch it would help, but I could not get it to compile.

**Comment by niktrop** [comment]
Did you find the following instruction? 
https://confluence.jetbrains.com/display/SCA/Setting+up+Scala+plugin+project+in+IntelliJ+IDEA
If so, what problems did you face with compilation?

We are going to publish new EAP build today or tomorrow, so you can just wait a little.

**Comment by niktrop** [comment]
You can try new EAP build:
https://confluence.jetbrains.com/display/SCA/Scala+plugin+EAP

**Comment by bblfish** [comment]
Thanks. The new EAP allows me to download the "scala-js spa tutorial" .  I'll try [your suggested fix for banana-rdf](https://github.com/w3c/banana-rdf/issues/258) in the next few days.

**Comment by cheptsov** [comment]
1
