### ISSUE TITLE
SBT file must only contain expressions

### ISSUE THREAD

**Issue by magic890** [JetBrains/intellij-scala#148]
My `build.sbt` file in a Play Framework 2 project contains the following line:

`lazy val server = (project in file(".")).enablePlugins(PlayScala)`

That is marked in red, with an error: "SBT file must only contain expressions".

IntelliJ IDEA 14.1.2
Build #IC-141.713
Scala plugin version: 1.4.15

This seems related to this old problem: [YouTrack](https://youtrack.jetbrains.com/issue/SCL-8060) and [GitHub](https://github.com/JetBrains/intellij-sbt/issues/8)

**Comment by nkly** [comment]
Hi! Thanks for the report. Yes, it is an old problem. I reopened related issue on Youtrack, please follow its progress.

**Comment by magic890** [comment]
Can you post the direct link to that issue on YouTrack?

**Comment by nkly** [comment]
@magic890 That's the one you've mentioned. I've reopened it yesterday.
