### ISSUE TITLE
Options to download sources but not docs

### ISSUE THREAD

**Issue by jongwook** [JetBrains/intellij-scala#152]
This is a feature request to add an option to download sources only, not docs, when importing or refreshing an IntelliJ SBT project.

I'm working in Asia where a round-trip-time to maven central sometimes take more than a second, which sometimes makes SBT takes hours to resolve the all dependencies of a big project like Apache Spark.

While downloaded sources are usually helpful for code browsing and debugging, doc downloads are rarely useful for me, as javadoc/scaladocs are already in the sources. But checking "Download sources and docs" triples SBT's dependency resolution time, which could've been just twice if I download the sources only.

So I thought it would be nice to have an option to download the sources only so that [it could save me some time during depenency resolution.](http://i.imgur.com/EenuByz.jpg)

**Comment by dancingrobot84** [comment]
Hi! Thanks for the suggestion. I've added your request to the [discussion on Youtrack](https://youtrack.jetbrains.com/issue/SCL-7412) and will close this issue in favour of that ticket.
