### ISSUE TITLE
ScalaTestConfigurationProducer doesn't configure location properly

### ISSUE THREAD

**Issue by fkorotkov** [JetBrains/intellij-scala#162]
From a JavaDoc of RunConfigurationProducer#setupConfigurationFromContext:

> sourceElement a reference to the source element for the run configuration (by default contains the element at caret, can be updated by the producer to point to a higher-level element in the tree).

Unfortunately ScalaTestConfigurationProducer doesn't configure it properly. It causes a problem in PreferredProducerFind#getConfigurationsFromContext. It picks only one configuration based on location(see ConfigurationFromContext.COMPARATOR).

The issue appears in any test class if JUnit support is enabled. TestClassConfigurationProducer produces a good configuration for a class with location set to ScClassImpl but ScalaTestConfigurationProducer doesn't change it and it persists to be some PsiWhiteSpace.

I'm expecting to see both producets produce run configuration with the same location so I can pick one myself.

**Comment by fkorotkov** [comment]
@jamesbrain was it fixed?

**Comment by jamesbrain** [comment]
@fkorotkov Yes, now both specs2 and scalaTest configuration producers set sourceElement to class containing the test.

**Comment by fkorotkov** [comment]
Perfect! Thank you!
