### ISSUE TITLE
@uncheckedVariance dosen't interpret ?

### ISSUE THREAD

**Issue by ImNotMyself** [JetBrains/intellij-scala#163]
Code snippet (I know that arrays are invariant but here just for sample):

``` scala
class Test[+T]{
  var arr: Array[T@uncheckedVariance] = null
}
```

The arr is marked red, with an error: Covariant type T occurs in invariant position in type Array[T] of value arr.

The class can be compiled by the Scala compiler.

IntelliJ IDEA 14.1.4
Build #IC-141.1532
intellij-scala @ 1.5.2

**Comment by ilinum** [comment]
I created a ticket on our issue tracker: https://youtrack.jetbrains.com/issue/SCL-8863
