### ISSUE TITLE
Unable to install Scala plugin

### ISSUE THREAD

**Issue by jawshooah** [JetBrains/intellij-scala#171]
When attempting to install the Scala plugin (v1.5.2) on a fresh install of IntelliJ IDEA 14.1.4 (Ultimate Edition), I get the following error:

```
Plugin Error: Scala: error in opening zip file
```

I'm not sure whether this is a problem with IntelliJ or the plugin, but I figured this would be a good place to report.

**Comment by Alefas** [comment]
What version of JVM do you use to run IntelliJ IDEA?

**Comment by Alefas** [comment]
If it's still an issue, please report here: https://youtrack.jetbrains.com/issues/SCL

**Comment by jawshooah** [comment]
Sorry about that, got it to work after several more attempts and forgot to report back.

**Comment by Alefas** [comment]
Is everything ok now?

**Comment by jawshooah** [comment]
Everything's working fine, yes. I can do a clean reinstall of the IDE and try again later if you'd like.

**Comment by Alefas** [comment]
No, it's not necessary, thank you!
