### ISSUE TITLE
Feature Request: Recognition of advanced compiler settings

### ISSUE THREAD

**Issue by TheRaspPie** [JetBrains/intellij-scala#175]
Hey,

I don't know if this is the right place for a feature request, but I'll post it anyway.

It would be great if the Scala IntelliJ Plugin could recognize compiler settings like -Yno-predef.
It's really annoying for me if I want to unimport everything except java.lang._ and IntelliJ still gives me autocompletion for it.

Thank you!

**Comment by m-elufimov-parc** [comment]
@TheRaspPie no, it's not. You can create FR in youtrack https://youtrack.jetbrains.com/issues/SCL

**Comment by Alefas** [comment]
You can create this feature request on YouTrack. We will do it at some point as it's not really complicated task, but it's out of priority for now.
What I can suggest you is to implement it faster by yourself.
As fast fix, you can just remove scala.Predef from ScalaFileImpl.DefaultImplicitlyImportedObjects then build your custom plugin. But if you add support to extract value from SBT script as additional setting, it will be good PR.
