### ISSUE TITLE
No Scala SDK in module - keeps popping up on every build configuration change

### ISSUE THREAD

**Issue by mostr** [JetBrains/intellij-scala#193]
Any change in SBT build files (like adding/removing dependencies) causes Idea to not being able to build project/run tests etc. Compilation (done with "Rebuild project") fails, with different error messages e.g. `Error:(6, 46) object FooBar is not a member of package x.y.z`. Openning `FooBar` causes the following warning/hint to popup (attaching screenshot). Setting Scala SDK fixes the issue but as it happens to every single module in the project it's a bit "counterproductive" to go to every single module and setup it's SDK every time build configuration changes. 

Is there a way to force Idea to remember this SDK setup and not asking for it every single time?
![no_scala_sdk](https://cloud.githubusercontent.com/assets/1169259/9171423/ac252b94-3f6b-11e5-98be-b25e095a4f13.png)

**Comment by mikolak-net** [comment]
+1 . This seems to occur mostly in projects that have > 10 modules.

**Comment by adamw** [comment]
+1 happens to me often as well. Often when importing a new project from existing sources, there are no modules, only after reloding the build config modules appear, but then without the sdk

**Comment by mkubala** [comment]
+1

**Comment by nkly** [comment]
Hi! Thanks for the report. Scala SDK should be detected automatically if language level of scala-library in your module dependencies match with the one detected from `scalaInstance` SBT setting. Could someone please attach an example project to reproduce this?

**Comment by imarios** [comment]
Have the same issue here. Thanks for taking care of this. 
I cannot post the entire project, but this might be helpful:

I have the Scala version defined outside of my project definitions at:
`scalaVersion in ThisBuild := "2.10.X"`

From running `show scalaInstance` I can see that the setting gets used by all the projects.

**Comment by nkly** [comment]
@imarios Thanks!

I've narrowed down the problem. Just to make sure that's the only one problem with Scala SDK, I'd like to ask you to do the following:
- Go to "Project Settings / Modules" dialog and select the module which does not have Scala SDK
- Find out what version of scala-library this module depends on
- Go to your build definition and change scalaVersion to this particular version
- Refresh project in IDEA

After the following steps Scala SDK should be set up automatically. Fix for this bug will appear in nightlies soon.

**Comment by imarios** [comment]
Hi Nikolay,
Here is what I have from one of the modules: 
![screen shot 2015-08-18 at 10 45 21 am](https://cloud.githubusercontent.com/assets/6893839/9337821/702e2966-4596-11e5-8691-9b1a23eb62c1.png)

One interesting thing is the presence of two different scala libraries. One in Compile and one in Test Scope. Only the scala version in the compile scope is the one I am are using. The other one I feel is a relic of the past. For some reason IntelliJ remembers it even though we took it out from SBT ...? 

![screen shot 2015-08-18 at 10 45 03 am](https://cloud.githubusercontent.com/assets/6893839/9337913/e642399e-4596-11e5-810e-f35ce90276e8.png)

**Comment by nkly** [comment]
@imarios I'm not quite understand your first screenshot. Do you mean that the module does not contain libraries at all?
As for the second point, I can't say definitely. Could you remove `.idea` directory and re-import your project in IDEA anew? Does outdated scala-library in Test scope appear after you do a fresh import?

**Comment by imarios** [comment]
I do have lots of libraries. The first screenshot just shows the beginning of my dependency list and shows you the Module SDK I am using. Let me try removing `.idea`. But overall I see this happens a lot. You import some library, then you stop using it, but IntelliJ keeps it in the module dependencies causing conflicts etc. I feel this is the same thing that happened here with the different Scala versions.

**Comment by imarios** [comment]
Update: I have done the cleanup of `.idea` directory and I am still getting the same problem. I currently have 15+ projects (if this has anything to do with the issue). Thanks!

**Comment by trulite** [comment]
This happens to me as well. Is there a fixed nightly that I can download?

**Comment by mostr** [comment]
@trulite There is no fix for it I'm aware of. I'm still yet to prepare sample project showing off this issue. Hope to have some time this week to finally do it.

**Comment by nkly** [comment]
Please, consider updating Scala plugin to 1.9.2 and re-importing your projects. Scala SDK detection should be fixed there.
