### ISSUE TITLE
Link the compilation error in project tree view

### ISSUE THREAD

**Issue by zjffdu** [JetBrains/intellij-scala#202]
I didn't see the compilation error in project tree view. It would be better to support it. Especially when the project is large, I'd like to see the impact of one file change on other files. 
http://stackoverflow.com/questions/32324629/how-can-i-see-scala-compilation-error-on-the-project-tree-of-intellij/32335009#32335009

**Comment by Alefas** [comment]
Please watch for the issue here: https://youtrack.jetbrains.com/issue/SCL-2340
