### ISSUE TITLE
ScalaJS React <. broken in Intellij 15 EAP

### ISSUE THREAD

**Issue by aparo** [JetBrains/intellij-scala#204]
The scalajs react [VDOM syntax <](https://github.com/japgolly/scalajs-react/blob/master/doc/USAGE.md#creating-virtual-dom).
It works perfectly in [scalajs-react project](https://github.com/japgolly/scalajs-react).
It works with IntelliJ 14.
It doesn't work in IntelliJ15 in every scalajs-react subproject for example [ScalaJS react Components](https://github.com/chandu0101/scalajs-react-components). The syntax is red and it's not usable.

Reproduction steps:

1) git clone https://github.com/chandu0101/scalajs-react-components
2) import the project in intellij idea 15 EAP
3) open for example demo/src/.../HomePage.scala

**Comment by Alefas** [comment]
Please follow https://youtrack.jetbrains.com/issue/SCL-9146
