### ISSUE TITLE
ScalaTestRunner: runs nested tests twice using 'all in package' testKind

### ISSUE THREAD

**Issue by vanDonselaar** [JetBrains/intellij-scala#207]
I'm using nested tests with ScalaTest as described here: http://doc.scalatest.org/2.0/index.html#org.scalatest.Suites

When I choose the `All in package` testKind it runs the nested tests twice. Once as part of the `StepsSuite` and once because of the individual class discovery. The nested tests are annotated with `@DoNotDiscover`, so the `sbt` command line runner skips the individual tests but IntelliJ does not.

This behavior is implemented here I think: https://github.com/JetBrains/intellij-scala/blob/f90ce96ebdc20ea14de4d63e04326c9246349b0a/src/org/jetbrains/plugins/scala/testingSupport/test/AbstractTestRunConfiguration.scala#L441

Instead of passing all individual class names to the ScalaTest command line using `-s`, I think the TestRunner should us the `-w` command line option described here: http://www.scalatest.org/user_guide/using_the_runner

I was not able to make a successful build of the Scala Plugin, but I think it should be something like this instead:

``` scala
if (testKind == TestKind.ALL_IN_PACKAGE) {
  printer.println("-w")
  printer.println(testPackagePath)
}
if (testKind == TestKind.CLASS) {
  printer.println("-s")
  for (cl <- getClasses) {
    printer.println(cl)
  }
}
```

**Comment by vanDonselaar** [comment]
I think this is the wrong issue tracker. Sorry. Here is the link to the Youtrack issue: https://youtrack.jetbrains.com/issue/SCL-9174

**Comment by Alefas** [comment]
Thank you for moving to the right place.
