### ISSUE TITLE
IntelliJ Scala/SBT ignores directories in unmanagedJars

### ISSUE THREAD

**Issue by NicolasRouquette** [JetBrains/intellij-scala#211]
Here is an example:

Create a project: ./P1 with the following:
- build.sbt

```
name := "P1"

version := "1.0"

scalaVersion := "2.11.7"
```
- src/main/scala/p1/Hello.scala

```
package p1

object Hello {

  def world: String =
    "Hello World!"
}
```

With IntelliJ or SBT, compile this project.
You'll get a folder with the compiled *.class files in ./P1/target/scala-2.11/classes

Next, create a project ./P2 with the following:
- build.sb

```
name := "P2"

version := "1.0"

scalaVersion := "2.11.7"

val extraDirs = settingKey[List[Attributed[File]]]("List of directories to add to the classpath")

extraDirs := List(Attributed.blank(new File("../P1/target/scala-2.11/classes")))

unmanagedJars in Compile <++= extraDirs map identity
```
- src/main/scala/o2/test.scala

```
package p2

import p1._

object test extends App {

  println("p2.test:" + Hello.world)
}
```

This compiles and runs fine with sbt.
It doesn't work with IntelliJ / Scala (version 14.1.5 + latest Scala or 15 EAP + latest Scala).

What surprises me is that this _used_ to work for many months until August 2015. Sometime in September 2015, some updates broke this first with 15 EAP and now with 14.1.5 as well.

**Comment by nkly** [comment]
Hi! Thanks for the report. This is a regression introduced during our move from `unmangedJars` to `unmanagedClasspath` usage. I created an issue in our tracker, you can follow its progress [here](https://youtrack.jetbrains.com/issue/SCL-9223).

**Comment by NicolasRouquette** [comment]
This works with IntelliJ 14.1.4 build IC-141-1532 + Scala 1.5.200

It does not work with IntelliJ 14.1.5 or with 15 EAP and recent versions of the Scala plugin.
