### ISSUE TITLE
Support for Scalastyle

### ISSUE THREAD

**Issue by janm399** [JetBrains/intellij-scala#62]
I'm adding Scalastyle support to the Scala plugin. The aim is to make it work as well as the Eclipse plugin. 

So far, my code only checks the Scala code and reports errors as expected. It uses the default Scalastyle configuration. 

I still need to add:
- Loading of custom configuration from the project's settings
- Improved error reporting in IDEA

https://github.com/janm399/intellij-scala

**Comment by tkellogg** [comment]
how do I know that IntelliJ loaded my `/scalastyle-config.xml` file?

**Comment by Alefas** [comment]
@tkellogg You can check with something, what IDEA doesn't report, but Scalastyle does. For example var definitions.
