### ISSUE TITLE
IntelliJ does not respect unmanagedSourceDirectories settings in sbt Build.scala

### ISSUE THREAD

**Issue by johanatan** [JetBrains/intellij-scala#69]
EOM.

**Comment by johanatan** [comment]
Hi,

Commenting here since I cannot comment in your other issue tracker. Is there any plan to fix this anytime soon? It would really make my workflow with Scala.js and Scala intermingled projects much nicer.

**Comment by Alefas** [comment]
That issue is marked as fixed in IDEA 14.
To comment issue you need to register, you just can't do it as Guest.
To improve workflow with Scala.js we have some plans, so it's probably will be done soon.
